#!/bin/bash
# link-brain.sh
# Symlinks this second-brain vault's .agents folder into a target project,
# and generates a .cursorrules + CLAUDE.md in that project pointing back at it.

# Set this to your vault's absolute path, or export VAULT_ROOT before running.
BRAIN_DIR="${VAULT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET_DIR="${1:-.}"

if [ ! -d "$TARGET_DIR" ]; then
    echo "Target directory '$TARGET_DIR' does not exist."
    exit 1
fi

TARGET_ABS=$(realpath "$TARGET_DIR")

echo "Symlinking .agents folder from '$BRAIN_DIR' to '$TARGET_ABS'..."
if [ -e "$TARGET_ABS/.agents" ] || [ -L "$TARGET_ABS/.agents" ]; then
    echo "  .agents already exists in target directory. Skipping symlink."
else
    ln -s "$BRAIN_DIR/.agents" "$TARGET_ABS/.agents"
    echo "  Symlinked .agents"
fi

# Configure .cursorrules
echo "Configuring .cursorrules in target..."
cat << EOF > "$TARGET_ABS/.cursorrules"
# Read instructions and style guidelines from this second brain vault.
# Reference: $BRAIN_DIR/.agents/AGENTS.md
# Reference: your domain mistakes log, if you keep one (e.g. Development/<Domain>/<Domain>-Mistakes.md)

You are an AI assistant working on this project. This project is linked to a
second-brain vault at $BRAIN_DIR.

CRITICAL DIRECTIVES:
1. Read the global rules in \`$BRAIN_DIR/.agents/AGENTS.md\` before starting.
2. Read any relevant mistakes/learnings log before coding.
3. Every time you fix a bug or write new code:
   - Output the corrected file.
   - Write a summary of the fix or framework mistake back to the vault's
     mistakes log, following the format described in that file.
EOF
echo "  Created .cursorrules"

# Configure CLAUDE.md (Claude Code reads this automatically from project root)
echo "Configuring CLAUDE.md in target..."
cat << EOF > "$TARGET_ABS/CLAUDE.md"
# Vault-Linked Agent Rules (auto-generated by link-brain.sh)

Before doing anything, read:
1. Global agent rules: $BRAIN_DIR/.agents/AGENTS.md
2. Relevant mistakes/learnings log for this kind of work, if one exists.

When you fix a bug or learn something new this session, save it to the vault:
- Domain-specific fixes → use the brain-sync skill (see .agents/skills/brain-sync)
- General fixes → append to your own General-Mistakes.md (create one if you don't have it yet)
EOF
echo "  Created CLAUDE.md"

# Slash commands and agent profiles
echo "Symlinking workflow commands and agents..."
mkdir -p "$TARGET_ABS/.claude"
if [ -e "$TARGET_ABS/.claude/commands" ] || [ -L "$TARGET_ABS/.claude/commands" ]; then
    echo "  .claude/commands already exists in target. Skipping."
else
    ln -s "$BRAIN_DIR/.claude/commands" "$TARGET_ABS/.claude/commands"
    echo "  Symlinked .claude/commands"
fi
if [ -e "$TARGET_ABS/.claude/agents" ] || [ -L "$TARGET_ABS/.claude/agents" ]; then
    echo "  .claude/agents already exists in target. Skipping."
else
    ln -s "$BRAIN_DIR/.claude/agents" "$TARGET_ABS/.claude/agents"
    echo "  Symlinked .claude/agents"
fi

echo "Brain linking completed for '$TARGET_ABS'."
